//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_info
    {
        public int Id { get; set; }
        public string book_name { get; set; }
        public string book_author { get; set; }
        public string book_publisher { get; set; }
        public Nullable<System.DateTime> book_purchase_date { get; set; }
        public Nullable<int> book_price { get; set; }
        public Nullable<int> book_quantity { get; set; }
        public string book_department { get; set; }
        public Nullable<int> available_quantity { get; set; }
    }
}
