//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_book
    {
        public int Id { get; set; }
        public string student_id { get; set; }
        public string book_name { get; set; }
        public string book_issue_date { get; set; }
        public string book_return_date { get; set; }
    }
}
