//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_info
    {
        public int Id { get; set; }
        public string student_name { get; set; }
        public string student_email { get; set; }
        public string student_contact { get; set; }
        public string student_department { get; set; }
        public string student_batch { get; set; }
        public string student_image { get; set; }
        public Nullable<System.DateTime> student_registration_date { get; set; }
    }
}
